Had to run "sudo pip3 install flask_pymongo" to avoid server to crash. 
For now will stick to this, however next time just make a venv bro

FOR TESTING, RUN:
sudo python3 main.py 

THIS WILL GIVE YOU THE ERROR INSTEAD OF "Internal Server Error"
